---
language: go
go:
- 1.2.2
- tip
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
  - DATABASE_URL=postgres://postgres@localhost:5432/travis
  - ARTIFACTS_BUCKET=meatballhat
  - secure: EEoQ0f9AJONcb6HxvSppI2dujwcnhVKQTiHsGanTEvHaAwvHNWSL7ORoYriWTQSzLIBCz+r8n4deOsqWwGZ0JgvkuHnyEZMQqKtWrBpl83DqpNoQn/cK65LnimW3hArQqT9v68WtvUDTF7Oiavt4Y/46nl1PhqVnVBn7gp1Tq1s=
  - secure: JrTponWNbo8M8I4+m/Kt+aPjRUXMlAf6gmbYvQnvY8QaY988KJuQ7mcPx05Qt2pXvF+YAl8VaS6eAbIu5hoFiN9ZHvW4Gf8gRkc0/mYvaKJXOKvgp3Bv72JIjhlaNqLU/w5nnuVP33Q21B6PftMaGhhDOVVKw0XkoxT24pk4UW8=
addons:
  postgresql: '9.3'
before_install:
- go get github.com/tools/godep
- go get code.google.com/p/go.tools/cmd/cover
- godep restore
- go install -a -race std
before_script:
- createdb -U postgres travis
script:
- make
- artifacts-service migrate
- ./integration-test file
- ./integration-test s3
deploy:
  provider: heroku
  buildpack: https://github.com/kr/heroku-buildpack-go.git
  api_key:
    secure: J2aEVgqBIdusX0Q2XmEI9lE/lcGdeHZluEdXJfenKD5fO4DTfWNvOT0yv0n3UyPsBiVbcluzvJHCZuEie0bIHWlIxaZ4hGVp+fitl5n47OhG6mexOXAJECxRero6STUca1NrNjEobVa0HkyNZaMyVcQpi9/nad1BIcZww5kX8ck=
  app: meatballhat-artifacts-service
  on:
    repo: hamfist/artifacts-service
